import Head from 'next/head'
import Image from 'next/image'
import HomepageHeroImage from '/public/intro.png'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
      <h1>This is a Big Title</h1>
      <Image
        src={HomepageHeroImage}
        layout="fill"
        objectFit="cover"
        objectPosition="center"
        alt="Beach view"
        placeholder="blur"
      />
      </main>
    </div>
  )
}
